package com.example.colorpickerdemo.viewmodel

import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel

class ColorPickerViewModel : ViewModel() {
    private val _selectedImageUrl = MutableLiveData<String>()

    val colorNames = arrayOf("Red", "Orange", "Yellow", "Green", "Cyan", "Blue", "Violet", "Magenta", "Rose", "Gold", "Lime", "Turquoise")
    val colorList = arrayListOf(
        Pair("Maroon","#800000"),
        Pair("DarkRed","#8B0000"),
        Pair("FireBrick","#B22222"),
        Pair("Red","#FF0000"),
        Pair("Salmon","#FA8072"),
        Pair("Tomato","#FF6347"),
        Pair("Coral","#FF7F50"),
        Pair("OrangeRed","#FF4500"),
        Pair("Chocolate","#D2691E"),
        Pair("SandyBrown","#F4A460"),
        Pair("DarkOrange","#FF8C00"),
        Pair("Orange","#FFA500"),
        Pair("DarkGoldenrod","#B8860B"),
        Pair("Goldenrod","#DAA520"),
        Pair("Gold","#FFD700"),
        Pair("Olive","#808000"),
        Pair("Yellow","#FFFF00"),
        Pair("YellowGreen","#9ACD32"),
        Pair("GreenYellow","#ADFF2F"),
        Pair("Chartreuse","#7FFF00"),
        Pair("LawnGreen","#7CFC00"),
        Pair("Green","#008000"),
        Pair("Lime","#00FF00"),
        Pair("LimeGreen","#32CD32"),
        Pair("SpringGreen","#00FF7F"),
        Pair("MediumSpringGreen","#00FA9A"),
        Pair("Turquoise","#40E0D0"),
        Pair("LightSeaGreen","#20B2AA"),
        Pair("MediumTurquoise","#48D1CC"),
        Pair("Teal","#008080"),
        Pair("DarkCyan","#008B8B"),
        Pair("Aqua","#00FFFF"),
        Pair("Cyan","#00FFFF"),
        Pair("DarkTurquoise","#00CED1"),
        Pair("DeepSkyBlue","#00BFFF"),
        Pair("DodgerBlue","#1E90FF"),
        Pair("RoyalBlue","#4169E1"),
        Pair("Navy","#000080"),
        Pair("DarkBlue","#00008B"),
        Pair("MediumBlue","#0000CD"),
        Pair("Blue","#0000FF"),
        Pair("BlueViolet","#8A2BE2"),
        Pair("DarkOrchid","#9932CC"),
        Pair("DarkViolet","#9400D3"),
        Pair("Purple","#800080"),
        Pair("DarkMagenta","#8B008B"),
        Pair("Fuchsia","#FF00FF"),
        Pair("Magenta","#FF00FF"),
        Pair("MediumVioletRed","#C71585"),
        Pair("DeepPink","#FF1493"),
        Pair("HotPink","#FF69B4"),
        Pair("Crimson","#DC143C"),
        Pair("Brown","#A52A2A"),
        Pair("IndianRed","#CD5C5C"),
        Pair("RosyBrown","#BC8F8F"),
        Pair("LightCoral","#F08080"),
        Pair("Snow","#FFFAFA"),
        Pair("MistyRose","#FFE4E1"),
        Pair("DarkSalmon","#E9967A"),
        Pair("LightSalmon","#FFA07A"),
        Pair("Sienna","#A0522D"),
        Pair("SeaShell","#FFF5EE"),
        Pair("SaddleBrown","#8B4513"),
        Pair("PeachPuff","#FFDAB9"),
        Pair("Peru","#CD853F"),
        Pair("Linen","#FAF0E6"),
        Pair("Bisque","#FFE4C4"),
        Pair("Burlywood","#DEB887"),
        Pair("Tan","#D2B48C"),
        Pair("AntiqueWhite","#FAEBD7"),
        Pair("NavajoWhite","#FFDEAD"),
        Pair("BlanchedAlmond","#FFEBCD"),
        Pair("PapayaWhip","#FFEFD5"),
        Pair("Moccasin","#FFE4B5"),
        Pair("Wheat","#F5DEB3"),
        Pair("Oldlace","#FDF5E6"),
        Pair("FloralWhite","#FFFAF0"),
        Pair("Cornsilk","#FFF8DC"),
        Pair("Khaki","#F0E68C"),
        Pair("LemonChiffon","#FFFACD"),
        Pair("PaleGoldenrod","#EEE8AA"),
        Pair("DarkKhaki","#BDB76B"),
        Pair("Beige","#F5F5DC"),
        Pair("LightGoldenrodYellow","#FAFAD2"),
        Pair("LightYellow","#FFFFE0"),
        Pair("Ivory","#FFFFF0"),
        Pair("OliveDrab","#6B8E23"),
        Pair("DarkOliveGreen","#556B2F"),
        Pair("DarkSeaGreen","#8FBC8F"),
        Pair("DarkGreen","#006400"),
        Pair("ForestGreen","#228B22"),
        Pair("LightGreen","#90EE90"),
        Pair("PaleGreen","#98FB98"),
        Pair("Honeydew","#F0FFF0"),
        Pair("SeaGreen","#2E8B57"),
        Pair("MediumSeaGreen","#3CB371"),
        Pair("Mintcream","#F5FFFA"),
        Pair("MediumAquamarine","#66CDAA"),
        Pair("Aquamarine","#7FFFD4"),
        Pair("DarkSlateGray","#2F4F4F"),
        Pair("PaleTurquoise","#AFEEEE"),
        Pair("LightCyan","#E0FFFF"),
        Pair("Azure","#F0FFFF"),
        Pair("CadetBlue","#5F9EA0"),
        Pair("PowderBlue","#B0E0E6"),
        Pair("LightBlue","#ADD8E6"),
        Pair("SkyBlue","#87CEEB"),
        Pair("LightSkyBlue","#87CEFA"),
        Pair("SteelBlue","#4682B4"),
        Pair("AliceBlue","#F0F8FF"),
        Pair("SlateGray","#708090"),
        Pair("LightSlateGray","#778899"),
        Pair("LightSteelBlue","#B0C4DE"),
        Pair("CornflowerBlue","#6495ED"),
        Pair("Lavender","#E6E6FA"),
        Pair("GhostWhite","#F8F8FF"),
        Pair("MidnightBlue","#191970"),
        Pair("SlateBlue","#6A5ACD"),
        Pair("DarkSlateBlue","#483D8B"),
        Pair("MediumSlateBlue","#7B68EE"),
        Pair("MediumPurple","#9370DB"),
        Pair("Indigo","#4B0082"),
        Pair("MediumOrchid","#BA55D3"),
        Pair("Plum","#DDA0DD"),
        Pair("Violet","#EE82EE"),
        Pair("Thistle","#D8BFD8"),
        Pair("Orchid","#DA70D6"),
        Pair("LavenderBlush","#FFF0F5"),
        Pair("PaleVioletRed","#DB7093"),
        Pair("Pink","#FFC0CB"),
        Pair("LightPink","#FFB6C1"),
        Pair("Black","#000000"),
        Pair("DimGray","#696969"),
        Pair("Gray","#808080"),
        Pair("DarkGray","#A9A9A9"),
        Pair("Silver","#C0C0C0"),
        Pair("LightGray","#D3D3D3"),
        Pair("Gainsboro","#DCDCDC"),
        Pair("WhiteSmoke","#F5F5F5"),
        Pair("White","#FFFFF"),

        )

    val selectedImageUrl: LiveData<String>
        get() = _selectedImageUrl

    fun setSelectedImage(url: String) {
        _selectedImageUrl.value = url
    }
}
